version: '3.8'
services:
  mongo:
    hostname: "mongo"  # custom host name to use for the service container
    container_name: "mongodb"  # specifies a custom container name
    image: "mongo:6.0.5"  # image to start the container from. Latest version on 05/2023 is 6.0.5
    restart: unless-stopped  # restarts a container irrespective of the exit code but will stop restarting when the service is stopped or removed
    ports:  # Exposes container ports: host IP, host port and container port
      - '27010:27010'
    volumes:  # mount host paths or named volumes that MUST be accessible by service containers
      - /opt/lst-safetybroker/db/mongo/WS:/data/db
    networks:
      weatherstation:
        aliases:
          - WSdatabase